services:
  benchmark-test:
    build:
      context: ..
      dockerfile: docker/benchmark-test/Dockerfile
      args:
        - DTPIPE_VERSION
        - SLING_VERSION
        - INGESTR_VERSION
    container_name: benchmark-test
    stdin_open: true
    tty: true
    volumes:
      - ../artifacts:/bench/artifacts
      - ../scripts:/bench/scripts
    networks:
      - benchmark-net

networks:
  benchmark-net:
    driver: bridge
